export const LOCALE_REPLACE ='LOCALE_REPLACE';
export const STATUS_REPLACE='STATUS_REPLACE';

export const USER_LOGIN ='USER_LOGIN';
export const USER_RESET ='USER_RESET';
export const USER_DETAILS_UPDATE ='USER_DETAILS_UPDATE';
export const USER_ERROR ='USER_ERROR';

export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';


export const LOAD_MORE_PRODUCTS_START = 'LOAD_MORE_PRODUCTS_START';
export const LOAD_MORE_PRODUCTS_SUCCESS = 'LOAD_MORE_PRODUCTS_SUCCESS';
export const LOAD_MORE_PRODUCTS_FAILURE = 'LOAD_MORE_PRODUCTS_FAILURE';

export const FETCH_PRODUCT_BY_ID_START = 'FETCH_PRODUCT_BY_ID_START';
export const FETCH_PRODUCT_BY_ID_SUCCESS = 'FETCH_PRODUCT_BY_ID_SUCCESS';
export const FETCH_PRODUCT_BY_ID_FAILURE = 'FETCH_PRODUCT_BY_ID_FAILURE';

export const ADD_PRODUCT_TO_BASKET_SUCCESS ='ADD_PRODUCT_TO_BASKET_SUCCESS';
export const ADD_PRODUCT_TO_BASKET_START ='ADD_PRODUCT_TO_BASKET_START';
export const ADD_PRODUCT_TO_BASKET_FAILURE ='ADD_PRODUCT_TO_BASKET_FAILURE';

export const SEARCH_PRODUCT_START = 'SEARCH_PRODUCT_START';
export const SEARCH_PRODUCT_SUCCESS ='SEARCH_PRODUCT_SUCCESS';
export const SEARCH_PRODUCT_FAILURE ='SEARCH_PRODUCT_FAILURE';

export const SET_ACTIVE_CATEGORY_ID ='SET_ACTIVE_CATEGORY_ID';

export const REMOVE_PRODUCT_FROM_BASKET_START = 'REMOVE_PRODUCT_FROM_BASKET_START';
export const REMOVE_PRODUCT_FROM_BASKET_SUCCESS ='REMOVE_PRODUCT_FROM_BASKET_SUCCESS';
export const REMOVE_PRODUCT_FROM_BASKET_FAILURE ='REMOVE_PRODUCT_FROM_BASKET_FAILURE';

export const REMOVE_ALLPRODUCT_FROM_BASKET_START = 'REMOVE_ALLPRODUCT_FROM_BASKET_START';
export const REMOVE_ALLPRODUCT_FROM_BASKET_SUCCESS ='REMOVE_ALLPRODUCT_FROM_BASKET_SUCCESS';
export const REMOVE_ALLPRODUCT_FROM_BASKET_FAILURE ='REMOVE_ALLPRODUCT_FROM_BASKET_FAILURE';

export const BASKET_CHECKOUT_START ='BASKET_CHECKOUT_START';
export const BASKET_CHECKOUT_SUCCESS ='BASKET_CHECKOUT_SUCCESS';
export const BASKET_CHECKOUT_FAILURE ='BASKET_CHECKOUT_FAILURE';
